---
title: "Table One"
author: "Chenxin Li"
date: "9/27/2019"
output:
  html_notebook:
    number_sections: yes
    toc: yes
    toc_float: yes
  html_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(ggplot2)
library(emmeans)
library(tidyr)
library(dplyr)
library(readr)
library(readxl)
library(vegan)
library(RColorBrewer)
library(stringr)
library(svglite)
```

#arrange
```{r}
table_1_data <- read_excel("C:/Users/cxli9/Desktop/Li/PBI/PBI299 (Sundar Lab)/smRNA project/CLVS_smRNA_revision/table_1_data.xlsx")
```
```{r}
head(table_1_data)
```
 
```{r}
table_1_left <- table_1_data[,1:2]
head(table_1_left)
```

```{r}
table_1_mid <- table_1_data[,c(1, 3:6)] %>% 
  gather("sample_type", "proportion", 2:5) %>% 
  mutate(sample_type = case_when(
    str_detect(sample_type, "seedling") ~ "seedling",
    str_detect(sample_type, "egg") ~ "egg",
    str_detect(sample_type, "sperm") ~ "sperm",
    str_detect(sample_type, "ovary") ~ "ovary"
  ))

head(table_1_mid)
```
```{r}
table_1_right <- table_1_data[,c(1, 7:10)] %>% 
  gather("sample_type", "enrichment", 2:5) %>% 
  mutate(sample_type = case_when(
    str_detect(sample_type, "seedling") ~ "seedling",
    str_detect(sample_type, "egg") ~ "egg",
    str_detect(sample_type, "sperm") ~ "sperm",
    str_detect(sample_type, "ovary") ~ "ovary"
  ))

head(table_1_right)
  
```
```{r}
table_1_df <- table_1_left %>% 
  full_join(table_1_mid, by = c("24nt siRNA loci")) %>% 
  full_join(table_1_right, by = c("24nt siRNA loci", "sample_type")) %>% 
  mutate(count_text = as.character(`loci count`)) %>% 
  mutate(pro_text = as.character(round(proportion * 100))) %>% 
  mutate(enrich_text = as.character(enrichment %>% 
                                      signif(2))) %>% 
  mutate(`24nt siRNA loci` = factor(`24nt siRNA loci`, levels = c(
    "intersection", 
    "sperm-egg_intersection",
    "sperm-seedling_intersection",
    "egg-seedling_intersection",
    "sperm_specific",
    "seedling_specific",
    "egg_specific",
    "sperm",
    "seedling",
    "egg"
  ))) %>% 
  mutate(sample_type = factor(sample_type, levels = c(
    "ovary", "egg", "seedling", "sperm"
  )))

table_1_df %>% head(10)
```

#plot
```{r}
#counts
left <- table_1_df %>% 
  ggplot(aes(y = `loci count`, x = `24nt siRNA loci`)) +
  geom_hline(yintercept = -Inf, size = 1.5) +
  geom_vline(xintercept = -Inf, size = 1.5) +
  geom_bar(stat = "identity", fill = "grey60", color = NA, alpha = 0.8) +
  geom_text(aes(label = count_text, y = 100), size = 5, hjust = 0, vjust = 0.5) +
  scale_y_continuous(labels = NULL) +
  scale_x_discrete(labels = NULL) +
  labs(y = NULL,
       x = NULL) +
  theme_minimal() +
  theme(text = element_text(size= 18, face="bold")) +
  theme(axis.text.x=element_text(colour = "black", angle = 45, hjust = 1)) +
  theme(axis.text.y=element_text(colour = "black")) +
  coord_flip()

left
```

```{r}
#proportions
mid <- table_1_df %>% 
  ggplot(aes(y = `24nt siRNA loci`, x = sample_type)) +
  geom_hline(yintercept = -Inf, size = 1.5) +
  geom_tile(aes(fill = proportion), alpha = 0.8) +
  geom_text(aes(label = pro_text), size = 5) +
  scale_fill_gradient(low = "white", high = "steelblue4") +
  scale_x_discrete(labels = NULL) +
  scale_y_discrete(labels = NULL) +
  labs(x = NULL,
       y = NULL) +
  theme_minimal() +
  theme(legend.position = "none") +
  theme(text = element_text(size= 18, face="bold")) +
  theme(axis.text.x=element_text(colour = "black")) +
  theme(axis.text.y=element_text(colour = "black"))   

mid
```
```{r}
#enrichment
right <- table_1_df %>% 
  ggplot(aes(y = `24nt siRNA loci`, x = sample_type)) +
  geom_hline(yintercept = -Inf, size = 1.5) +
  geom_tile(aes(fill = enrichment), alpha = 0.8) +
  geom_text(aes(label = enrich_text), size = 5) +
  scale_x_discrete(labels = NULL) +
  scale_y_discrete(labels = NULL) +
  scale_fill_gradient(low = "white", high = "steelblue4") +
  labs(x = NULL,
       y = NULL) +
  theme_minimal() +
  theme(legend.position = "none") +
  theme(text = element_text(size= 18, face="bold")) +
  theme(axis.text.x=element_text(colour = "black")) +
  theme(axis.text.y=element_text(colour = "black"))

right
```

```{r}
#arrange them
library(cowplot)
```
```{r}
table_1 <- plot_grid(left, NULL,  mid, NULL, right, nrow = 1, rel_widths = c(0.4, -0.02, 1, -0.02, 1))
table_1

ggsave("table_1.svg", height = 2.8, width = 8.5)
ggsave("table_1.png", height = 2.8, width = 8.5)
```


Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
